### ISSUE TITLE
Mini Node V2 - ADC Voltage Conversion

### ISSUE THREAD

**Issue by ActuonixElec** [RaccoonlabDev/mini_v2_node#13]
I am wondering what equation you are using to convert between the ADC readings on PA0 & PA1 (Vin & 5V3) and a floating-point voltage value.  I'd like to replicate this capability you have in the Mini Node V2 firmware in my custom application.

**Comment by PonomarevDA** [comment]
Hi. It can be calculated as:

```c++
#define ADC_RAW_TO_5V  (3.3f * 2.0f / 4095.0f)
#define ADC_RAW_TO_VIN (3.3f * 19.0f / 4095.0f)

float voltage_5v = AdcPeriphery::get(AdcChannel::ADC_5V) * ADC_RAW_TO_5V;
float voltage_vin = AdcPeriphery::get(AdcChannel::ADC_VIN) * ADC_RAW_TO_VIN;
```

I will try to give an example later.

**Comment by ActuonixElec** [comment]
That's great, thank you!
