### ISSUE TITLE
How to build project on Windows?

### ISSUE THREAD

**Issue by sainquake** [RaccoonlabDev/mini_v2_node#3]
The instrution is aimed to work under Ubuntu, but someone maybe work under Windows.

I investigate how to run it under Windows. I used next:
- VS Code 
- WSL2
- GDB Programmer like Black Magic or Dronecode probe and st-link programmer

Also I have used [usbipd](https://github.com/dorssel/usbipd-win) to forward USB device to WSL. This [instruction](https://github.com/dorssel/usbipd-win/wiki/WSL-support) also needed to run it.

**Comment by PonomarevDA** [comment]
@sainquake, I've added a windows build example in CI. Please, check it out #39.
