### ISSUE TITLE
Arming status does not change its mode

### ISSUE THREAD

**Issue by AsiiaPine** [RaccoonlabDev/mini_v2_node#68]
As default any Module have ```Mode mode{Mode::INITIALIZATION};```[source code](https://github.com/RaccoonlabDev/mini_v2_node/blob/ca2b9e443bc2dee7fc2c5d97a4a877d2e68dfed7/Src/common/module.hpp#L85) 
Therefore, the node does not leave INITIALIZATION state

Proofs:
I added logging of modules mode for each registered module and got the following messages:
![image](https://github.com/user-attachments/assets/10b342ff-d887-4225-ac23-15a925770d21)

**Comment by PonomarevDA** [comment]
I tried it on the main branch and it looks fine. Arming module doesn't provide an implementation for init() method ([arming.hpp](https://github.com/RaccoonlabDev/mini_v2_node/blob/3523d6a045af0afa90ea71a5bfad751539196872/Src/modules/dronecan/arming/arming.hpp)), so it uses the implementation from the base class ([module.cpp](https://github.com/RaccoonlabDev/mini_v2_node/blob/3523d6a045af0afa90ea71a5bfad751539196872/Src/common/module.cpp#L16)).

Could you clarify the firmware version?
