### ISSUE TITLE
ArrayCommand do not send EscStatus

### ISSUE THREAD

**Issue by olegogogo** [RaccoonlabDev/mini_v2_node#71]
[firmware version](https://github.com/RaccoonlabDev/docs/releases/tag/v0.12.2)

while EscCommand is able to send log feedback:
![изображение](https://github.com/user-attachments/assets/4cb91f0e-3813-4b43-a28c-bc7170d2e027)

ArrayCommand do not send EscStatus
![изображение](https://github.com/user-attachments/assets/0c837b85-6e37-4cdb-bb93-f07f216b19ce)

| №  | Parameter               | Type    | Default | Current | Min  | Max        |
|----|-------------------------|---------|---------|---------|------|------------|
| 0  | uavcan.node.id           | integer | 21      | 42      | 0    | 255        |
| 1  | system.can_terminator    | integer | 0       | 0       | 0    | 3          |
| 2  | system.protocol          | integer | 0       | 0       | 0    | 2          |
| 3  | system.log_level         | integer | 1       | 3       | 0    | 4          |
| 4  | stats.engaged_time       | integer | 1681    | 0       | 0    | 2147483647 |
| 5  | crct.bitmask             | integer | 15      | 15      | 0    | 15         |
| 6  | feedback.type            | integer | 1       | 0       | 0    | 2          |
| 7  | pwm.cmd_ttl_ms           | integer | 500     | 500     | 0    | 10000      |
| 8  | pwm.frequency            | integer | 50      | 50      | 50   | 400        |
| 9  | pwm1.ch                 | integer | 4       | -1      | -1   | 255        |
| 10 | pwm1.min                 | integer | 1000    | 1000    | 1000 | 2000       |
| 11 | pwm1.max                 | integer | 2000    | 2000    | 1000 | 2000       |
| 12 | pwm1.def                 | integer | 1000    | 1000    | 1000 | 2000       |
| 13 | pwm2.ch                 | integer | -1      | -1      | -1   | 255        |
| 14 | pwm2.min                 | integer | 1000    | 1000    | 1000 | 2000       |
| 15 | pwm2.max                 | integer | 2000    | 2000    | 1000 | 2000       |
| 16 | pwm2.def                 | integer | 1000    | 1000    | 1000 | 2000       |
| 17 | pwm3.ch                 | integer | -1      | -1      | -1   | 255        |
| 18 | pwm3.min                 | integer | 1000    | 1000    | 1000 | 2000       |
| 19 | pwm3.max                 | integer | 2000    | 2000    | 1000 | 2000       |
| 20 | pwm3.def                 | integer | 1000    | 1000    | 1000 | 2000       |
| 21 | pwm4.ch                 | integer | -1      | -1      | -1   | 255        |
| 22 | pwm4.min                 | integer | 1000    | 1000    | 1000 | 2000       |
| 23 | pwm4.max                 | integer | 2000    | 2000    | 1000 | 2000       |
| 24 | pwm4.def                 | integer | 1000    | 1000    | 1000 | 2000       |
| 25 | pwm.cmd_type             | integer | 1       | 0       | 0    | 2          |
| 26 | uavcan.node.description  | string  | arl.kirpi.v2.3.0 |       |      |            |
| 27 | system.name              | string  |         |         |      |            |

**Comment by PonomarevDA** [comment]
If you use esc.RawCommand, you will get esc.Status.
If you use actuator.ArrayCommand, you will get actuator.Status.
This is by design.
