### ISSUE TITLE
Doubled modules frequency

### ISSUE THREAD

**Issue by AsiiaPine** [RaccoonlabDev/mini_v2_node#92]
Commit: 932a58
The system is structured using various modules that operate at different frequencies. However, during testing, I observed that the frequency at which these modules operate is unexpectedly doubled.

# Steps to Reproduce:

Build the project from commit <commit-hash> (shown in the video).

Run the system and observe the module frequencies via a video capture of the monitor.

Notice the circuit status messages, which should be published twice per second, but are instead published four times per second.

# Expected Behavior:

The circuit status message should be sent at its intended frequency of 2 times per second.

# Actual Behavior:

The circuit status message is incorrectly sent 4 times per second, indicating a frequency doubling issue.
______
Additional Information:

A video capturing the monitor output has been attached, illustrating the commit from which the project was built and the unexpected frequency behavior.

[Screencast from 12-06-2024 03:11:48 PM.webm](https://github.com/user-attachments/assets/4c658189-7532-43e8-9002-b45bf7c7cfb4)

**Comment by PonomarevDA** [comment]
The circuit status module publishes 2 messages with different circuit id. First with 5v, second with vin.
